# Generated by Django 5.2.8 on 2025-11-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الطالب')),
                ('level', models.CharField(choices=[('bachelor', 'بكالوريوس'), ('master', 'دراسات عليا (ماجستير)'), ('phd', 'دراسات عليا (دكتوراه)')], max_length=20, verbose_name='المستوى الدراسي')),
                ('order', models.IntegerField(default=1, verbose_name='ترتيب العضو')),
            ],
            options={
                'verbose_name': 'عضو فريق',
                'verbose_name_plural': 'أعضاء الفرق',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader_email', models.EmailField(max_length=254, unique=True, verbose_name='إيميل قائد الفريق')),
                ('project_field', models.CharField(choices=[('health', 'الصحة'), ('energy', 'الطاقة'), ('environment', 'البيئة')], max_length=20, verbose_name='مجال المشروع')),
                ('project_category', models.CharField(choices=[('student_research', 'مشروع بحثي طلابي'), ('published_research', 'بحث علمي منشور'), ('prototype', 'نموذج أولي'), ('science_communication', 'تعريب وتبسيط العلوم')], max_length=30, verbose_name='فئة المشروع')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='موافقة على الشروط')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('members', models.ManyToManyField(related_name='registrations', to='registrations.teammember', verbose_name='أعضاء الفريق')),
            ],
            options={
                'verbose_name': 'تسجيل فريق',
                'verbose_name_plural': 'تسجيلات الفرق',
                'ordering': ['-registration_date'],
            },
        ),
    ]
