# Generated by Django 5.2.8 on 2025-11-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Team Registration', 'verbose_name_plural': 'Team Registrations'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='accept_terms',
            field=models.BooleanField(default=False, verbose_name='Accept Terms'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='members',
            field=models.ManyToManyField(related_name='registrations', to='registrations.teammember', verbose_name='Team Members'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='project_category',
            field=models.CharField(choices=[('student_research', 'Student Research Project'), ('published_research', 'Published Scientific Research'), ('prototype', 'Prototype'), ('science_communication', 'Science Translation and Simplification')], max_length=30, verbose_name='Project Category'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='project_field',
            field=models.CharField(choices=[('health', 'Health'), ('energy', 'Energy'), ('environment', 'Environment')], max_length=20, verbose_name='Project Field'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_leader_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Team Leader Email'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='level',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Graduate Studies (Master)'), ('phd', 'Graduate Studies (PhD)')], max_length=20, verbose_name='Academic Level'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Member Order'),
        ),
    ]
